# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 640db13fceb201cf00ee90423493d5f9e7e6337be875f46c98efa97da95564400d45a2a2b8feacadce66668866db2b93e49aab83b9a32f2b571a64ea60bfb815

test:
  secret_key_base: b4ff46d0ad1f0620c1e6db86f89c46781ad0eec791d1e9e96f5aa5b83c1ab4a735f68bd7444c49d90f9b9631a959565e1f7876a9ee9ba0d42e781d996cb89168

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
